### ISSUE TITLE
Multiple instance is based on wrong assumption about the callback function pointer lifespan

### ISSUE THREAD

**Issue by lausdahl** [controllab/fmi-export-20sim#16]
The multi instance support assumes that the `const fmi2CallbackFunctions* functions` is available and points to a valid memory location during the library life time. 

When I run two simulations in the same process with matching end time it works (by luck) but if one of the simulations has a longer simulation time then it crashes in `freeInstance`. By inspecting the code it seems like you store the `fmi2CallbackFunctions` pointer in a global variable `g_fmiCallbackFunctions` instead of inside the instance. Therefore field `g_fmiCallbackFunctions` is overriden by the fast running simulation and when the longer running simulation terminates it may happen medially after the location which `g_fmiCallbackFunctions` points to have been freed, and right before instantiate again is called resetting it to a valid memory address. 

The COE in into-cps creates a callback object per instance and frees this after the instance is freed.

I modified the generated code to look like:

``` C
void fmi2FreeInstance(fmi2Component c) 
{
    XXModelInstance* xx_model_instance = (XXModelInstance*) c;

    if (xx_model_instance->resourceLocation != NULL)
    {
        //g_fmiCallbackFunctions->freeMemory
        free((void*)xx_model_instance->resourceLocation);
        xx_model_instance->resourceLocation = NULL;
    }

    if(xx_model_instance->instanceName != NULL)
    {
        //g_fmiCallbackFunctions->freeMemory
        free((void *)xx_model_instance->instanceName);
        xx_model_instance->instanceName = NULL;
    }
    //g_fmiCallbackFunctions->freeMemory
    free((void *) xx_model_instance);
    xx_model_instance =  NULL;
}
```

and ran two simulations simultaneously `873` and `1061` times without any issues with the fix shown above directly calling free to avoid using the global field (it should probably have been stored inside the instance instead). Without it I can run between 1 and 3.

**Comment by margro** [comment]
Thanks for reporting. We will fix this.
Your direct use of free() is course a workaround to prove where the issue is. We should use the freeMemory() function from the callback functions instead.
From your description, it is enough for us to store the callback functions inside our xx_model_instance object and we can still use them inside the fmi2FreeInstance() function to free our resources.
