### ISSUE TITLE
Missing start values of variables

### ISSUE THREAD

**Issue by yingguangchu** [controllab/fmi-export-20sim#39]
Referring to FMI 2.0.1 standard page 56: “Variables with causality = "parameter" or "input", as well as variables with variability = "constant", must have a "start" value.”

We noted that the exporter (standalone) doesn't register start values for the followings:
causality="local" variability="constant"
causality="input" variability="continuous"
causality="output" variability="continuous"

**Comment by margro** [comment]
Hi Yingguang,

Are you using this github template or the version delivered with 20-sim itself? If you are using the 20-sim version, which version of 20-sim are you using?

Kind regards,
Marcel

**Comment by yingguangchu** [comment]
Hi Marcel
It is with the version delivered with 20-sim 4.8.1.  
Best, 
Yingguang

**Comment by margro** [comment]
Hi Yingguang,

Controllab has released a new version of 20-sim, version 4.8.2, that should fix this issue.
You can download this version from our website [https://www.20sim.com/downloadnext/](url)
