### ISSUE TITLE
Table 2D not including data file when exported

### ISSUE THREAD

**Issue by CarlGamble** [controllab/fmi-export-20sim#6]
The default way to specify the data file for table 2d to use is to right click and set the file name in the parameters menu, however if you do this the exported fmu does not contain the data file.

In the line follow sensors and the fan coil unit we had to add the file name directly into the parameters section (as below) and then the FMU export script correctly copies the data file when it creates the FMU.

`parameters
    string table_file_name = 'ratSP5WorkingDays_2column.txt';`

**Comment by MaartenMJR** [comment]
Hi Carl,

Thank you for notifying us. We have found that this is due to a bug in 20-sim for string parameters in code generation.

This will be fixed in our next 4.6.2 release.

**Comment by margro** [comment]
4.6.2-intocps and 4.6.2 contain a fix for this.
